import CueIds from "./CueIds";

const willCues = [
  {
    cue: `Hello! What is your full legal name?`,
    inputType: "text",
    cueId: CueIds.YourName,
    inputIsVisible: true,
  },
  {
    cue: `Great!`,
    para: `We just need you to answer some questions to draft a will for you. A will designates a person (an executor) to distribute your stuff to your heirs after you pass away.`,
    inputIsVisible: false,
  },
  {
    cue: `What is the name of the city or town where you reside?`,
    para: `Simply include the name and province, e.g. "Gibsons, British Columbia."`,
    inputType: "text",
    cueId: CueIds.YourCity,
    inputIsVisible: true,
  },
  // {
  //   cue: "",
  //   para: `When you sign your will, any previous will you've made will be cancelled.`,
  //   inputIsVisible: false,
  // },
  {
    cue: "What is the full name of your executor?",
    para: `You'll need to appoint an executor for your will. This person will distribute your stuff to your heirs. You should appoint someone who is unlikely to die before you (so someone healthy, around your age or younger). Ideally this person has some experience dealing with business or legal affairs.`,
    inputType: "text",
    cueId: CueIds.ExecutorName,
    inputIsVisible: true,
  },
  {
    cue: `What is the relationship of your executor to you?`,
    para: `Is this person your spouse? Sister? Friend? Note this here.`,
    inputType: "text",
    cueId: CueIds.ExecutorRelation,
    inputIsVisible: true,
  },
  {
    cue: `What is the name of the city or town where your executor resides?`,
    para: `Name the city and province. For example: "Vancouver, British Columbia".`,
    inputType: "text",
    cueId: CueIds.ExecutorCity,
    inputIsVisible: true,
  },
  {
    cue: "What is the full name of your alternate executor?",
    para: `If your appointed executor is at any time unwilling or incapable of acting as your executor, your alternate can take over.`,
    inputType: "text",
    cueId: CueIds.AltExecutorName,
    inputIsVisible: true,
  },
  {
    cue: `What is the relationship of your alternate executor to you?`,
    para: `Is this person your wife? Son? Friend? Note this here.`,
    inputType: "text",
    cueId: CueIds.AltExecutorRelation,
    inputIsVisible: true,
  },
  {
    cue: "In what city and province does your alternate executor reside?",
    para: `For example: "Victoria, British Columbia."`,
    inputType: "text",
    cueId: CueIds.AltExecutorCity,
    inputIsVisible: true,
  },
  {
    cue: "Who do you want to inherit your stuff?",
    para: `The property you distribute to your heir is called your "estate".`,
    inputType: "text",
    cueId: CueIds.HeirName,
    inputIsVisible: true,
  },
  {
    cue: "What is your heir's relationship to you?",
    para: `For example: "Son", "Daughter", or "Sister".`,
    inputType: "text",
    cueId: CueIds.HeirRelation,
    inputIsVisible: true,
  },
  {
    cue: "In what city and province does your heir reside?",
    para: `For example: "Burnaby, British Columbia."`,
    inputType: "text",
    cueId: CueIds.HeirCity,
    inputIsVisible: true,
  },
  {
    cue: "If your heir passes away before you, who do you want to inherit your estate?",
    para: `Name an alternate heir`,
    inputType: "text",
    cueId: CueIds.AltHeirName,
    inputIsVisible: true,
  },
  {
    cue: "What is your alternate heir's relationship to you?",
    para: `Son? Daughter? Wife?`,
    inputType: "text",
    cueId: CueIds.AltHeirRelation,
    inputIsVisible: true,
  },
  {
    cue: "In what city does your alternate heir live?",
    para: `For example: "Kelowna, British Columbia"`,
    inputType: "text",
    cueId: CueIds.AltHeirCity,
    inputIsVisible: true,
  },
  {
    cue: "After I die, I want my body to be:",
    para: `You can type here "cremated" or "buried" depending on your preference.`,
    inputType: "text",
    cueId: CueIds.DispositionOfRemains,
    inputIsVisible: true,
  },
];

export default willCues;
